contacts_v0.1
AlexBychkov/textme pull request #5
Opened 2020-10-21 19:19 UTC by valerasam

2020-10-23 09:32 UTC, AlexBychkov approved these changes

2020-10-23 09:32 UTC, AlexBychkov commented on src/App.js
> +        <Redirect from='/' to='/home' />
think, it's better to move <Redirect from='/' to='/home' /> to the bottom of Switch to have it more readable

2020-10-26 07:46 UTC, foxprogs approved these changes

2020-10-26 09:52 UTC, AlexBychkov requested changes

2020-10-26 09:52 UTC, AlexBychkov commented on src/pages/contact/Contact.js
> +                <TableCell>
it's beter to have this in one line like in lines 15 or 16

2020-10-26 09:52 UTC, AlexBychkov commented on src/pages/contact/Contact.js
> +
lets' remove all except one new lines

2020-10-26 09:52 UTC, AlexBychkov commented on src/components/menuUser/MenuUser.js
> +  //style for link
let's move styles to the bottom of this component

2020-10-26 09:52 UTC, AlexBychkov commented on src/components/header/Header.js
> +const useStyles = makeStyles((theme) => ({
let's move styles to a separate file, like in PR number 6

2020-10-26 17:40 UTC, merged