Develop
AlexBychkov/textme pull request #6
Opened 2020-10-25 18:06 UTC by Djon-Latii

Please see my changes. 
Added paths and changed the project structure

2020-10-25 18:29 UTC, Nicelx approved these changes

2020-10-26 09:52 UTC, AlexBychkov requested changes

2020-10-26 09:52 UTC, AlexBychkov commented on src/pages/contactList/ContactList.js
> +            <div className="contact-list" style={{width: '100%',
let's move this style to a separate file like ContactList.css

2020-10-26 09:52 UTC, AlexBychkov commented on src/App.js
> +          {true ? <Home /> : <Redirect from='/' to="/login" />}
hm, I think there we should have all the components and routes, for example ContactList

2020-10-26 10:04 UTC, Djon-Latii commented on src/App.js
> +          {true ? <Home /> : <Redirect from='/' to="/login" />}
I transferred all components to Home. This componet see only registуred user

2020-10-26 10:17 UTC, Djon-Latii commented on src/App.js
> +          {true ? <Home /> : <Redirect from='/' to="/login" />}
![image](https://user-images.githubusercontent.com/57762960/97160511-23952c00-1785-11eb-9709-9eeb4db50a2a.png)

2020-10-26 19:16 UTC, merged